version: "2"

# -----------------------------------------------------------------------------
# FORMATTERS
# The "Latest & Greatest" separation of concerns.
# These tools modify your code (rewrite/fix) to ensure strict style.
# -----------------------------------------------------------------------------
formatters:
  enable:
    - gofumpt    # Stricter than gofmt
    - gci        # Strict import sorting
    - golines    # Strict line length (fixes lines > 120)

  settings:
    # gofumpt: strict formatting rules
    gofumpt:
      extra-rules: true
      module-path: mddiff # Set this for optimal grouping

    # gci: deterministic import ordering
    gci:
      custom-order: true
      sections:
        - standard
        - default
        - prefix(mddiff) # Groups your internal modules separately

    # golines: shortens long lines
    golines:
      max-len: 120

# -----------------------------------------------------------------------------
# LINTERS
# These tools analyze your code for bugs, complexity, and performance.
# -----------------------------------------------------------------------------
linters:  
  enable:
    # -- The Essentials --
    - errcheck    # Mandates that you handle all errors
    - modernize   # Suggests simplifications to Go code, using modern language and library features
    - govet       # Official Go vet tool
    - ineffassign # Detects unused assignments
    - staticcheck # The gold standard for Go static analysis
    - unused      # Finds unused variables/constants/functions

    # -- Strict Style & Quality --
    - revive      # Faster, stricter replacement for golint
    - gocritic    # Catches bugs and performance issues (very strict)
    - godot       # Enforces comments end with a period (very pedantic!)
    - misspell    # Fixes typos in comments
    - whitespace  # Detects leading/trailing whitespace

    # -- Complexity & Perf --
    - gocyclo     # Cyclomatic complexity checks (fail if function is too complex)
    - prealloc    # Suggests pre-allocating slices (performance)
    - noctx       # Ensures you pass context.Context to functions that need it

    # -- Security --
    - gosec       # Security scanner (hardcoded credentials, weak crypto, etc.)

# -----------------------------------------------------------------------------
# LINTER SETTINGS
# -----------------------------------------------------------------------------
  settings:
    # Revive is the modern "golint". We configure it to be opinionated.
    revive:
      severity: error
      rules:
        - name: exported
          disabled: false
          arguments:
            - checkPrivateReceivers
        - name: package-comments
          disabled: false
        - name: error-naming
          disabled: false

    # Fail if a function has a complexity score > 15
    gocyclo:
      min-complexity: 15

    # Gocritic is a collection of "critics". We enable the important tags.
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style

    # Security checks
    gosec:
      excludes:
        - G104 # We use 'errcheck' for this instead, so duplicate ignore

issues:
  # Maximum issues count per one linter. Set to 0 to disable.
  max-issues-per-linter: 0
  # Maximum count of issues with the same text. Set to 0 to disable.
  max-same-issues: 0